version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
  open-pull-requests-limit: 30
  assignees:
  - Chesire

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
  open-pull-requests-limit: 30
  assignees:
  - Chesire

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
  open-pull-requests-limit: 30
  assignees:
  - Chesire
