# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new Alpha Build to the Play Store"
  lane :alpha do
    gradle(
      task: 'clean assemble',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'alpha',
      validate_only: 'true'
      #mapping: '' - Will add this later
    )
  end
end
