package com.chesire.malime

// Login
const val VALID_USERNAME = "VALID_USERNAME"
const val INVALID_USERNAME = "INVALID_USERNAME"
const val VALID_PASSWORD = "VALID_PASSWORD"
const val INVALID_PASSWORD = "INVALID_PASSWORD"

// Search
const val VALID_SEARCH_NO_ITEMS = "VALID_SEARCH_NO_ITEMS"
const val VALID_SEARCH_SINGLE_ITEM = "VALID_SEARCH_SINGLE_ITEM"
const val VALID_SEARCH_MULTIPLE_ITEMS = "VALID_SEARCH_MULTIPLE_ITEMS"
const val VALID_SEARCH_ADD_TITLE = "VALID_SEARCH_ADD_TITLE"
const val INVALID_SEARCH = "INVALID_SEARCH"
const val INVALID_SEARCH_ADD_TITLE = "INVALID_SEARCH_ADD_TITLE"
