package com.chesire.malime

// Login
const val VALID_USERNAME = "VALID_USERNAME"
const val INVALID_USERNAME = "INVALID_USERNAME"
const val VALID_PASSWORD = "VALID_PASSWORD"
const val INVALID_PASSWORD = "INVALID_PASSWORD"

// Search
const val VALID_SEARCH = "VALID_SEARCH"
const val INVALID_SEARCH = "INVALID_SEARCH"
const val INVALID_SEARCH_NO_ITEMS = "INVALID_SEARCH_NO_ITEMS"