package com.chesire.malime

const val VALID_USERNAME = "VALID_USER"
const val INVALID_USERNAME = "INVALID_USER"
const val VALID_PASSWORD = "VALID_PASSWORD"
const val INVALID_PASSWORD = "INVALID_PASSWORD"