name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.0.13
    - name: upload test results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: app/build/reports/
    - name: upload test xml
      uses: actions/upload-artifact@v2
      with:
        name: test_xml
        path: app/build/test-results/

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew app:lintDebug
    - name: run detekt
      run: ./gradlew detekt
    - name: upload linting results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: build/reports/

  danger:
    needs: [test, analyze]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
    - uses: actions/setup-ruby@v1.1.1
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.4
      run: gem install bundler:2.1.4
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: download lint results
      uses: actions/download-artifact@v2
      with:
        name: lint
        path: build/reports/
    - uses: MeilCli/danger-action@v5.0.0
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
