name: Pre-Merge

on:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run assemble
      run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.2.2

  ktlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: run detekt
      run: ./gradlew detekt
    - uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.4
      run: gem install bundler:2.1.4
    - uses: actions/cache@v2.1.4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: MeilCli/danger-action@v5.1.0
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
