name: Pre-Merge

on:
  pull_request_target:
    branches: [ '*' ]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run assemble
      run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.2.0

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew app:lintDebug
    - name: run detekt
      run: ./gradlew detekt
    - name: upload linting results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: build/reports/

  danger:
    needs: [test, analyze]
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - uses: actions/setup-ruby@v1.1.2
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.4
      run: gem install bundler:2.1.4
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: download lint results
      uses: actions/download-artifact@v2
      with:
        name: lint
        path: build/reports/
    - uses: MeilCli/danger-action@v5.0.3
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
